services:
  redis_uuid:
    image: redis:latest
    container_name: redis_uuid
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-uuid:/data

volumes:
  redis-uuid: