// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	errs "github.com/raffops/chat/internal/errs"
	mock "github.com/stretchr/testify/mock"

	models "github.com/raffops/chat/internal/models"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, user
func (_m *Repository) Create(ctx context.Context, user models.User) (models.User, *errs.Err) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.User
	var r1 *errs.Err
	if rf, ok := ret.Get(0).(func(context.Context, models.User) (models.User, *errs.Err)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.User) models.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.User) *errs.Err); ok {
		r1 = rf(ctx, user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.Err)
		}
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, name
func (_m *Repository) Get(ctx context.Context, name string) (models.User, *errs.Err) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.User
	var r1 *errs.Err
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.User, *errs.Err)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.User); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *errs.Err); ok {
		r1 = rf(ctx, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.Err)
		}
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
