// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeLoginServer is an autogenerated mock type for the UnsafeLoginServer type
type UnsafeLoginServer struct {
	mock.Mock
}

// mustEmbedUnimplementedLoginServer provides a mock function with given fields:
func (_m *UnsafeLoginServer) mustEmbedUnimplementedLoginServer() {
	_m.Called()
}

// NewUnsafeLoginServer creates a new instance of UnsafeLoginServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeLoginServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeLoginServer {
	mock := &UnsafeLoginServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
